import datetime
import random
from database.database import SessionLocal, engine, Base
from database import models
from passlib.context import CryptContext

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def get_password_hash(password):
    return pwd_context.hash(password)

def seed_data():
    # Ensure tables exist
    Base.metadata.create_all(bind=engine)
    
    # Run database migrations for new columns
    from sqlalchemy import text, inspect
    print("Running database migration for verification fields...")
    try:
        inspector = inspect(engine)
        if inspector.has_table("users"):
            columns = [col["name"] for col in inspector.get_columns("users")]
            with engine.connect() as conn:
                if "is_verified" not in columns:
                    conn.execute(text("ALTER TABLE users ADD COLUMN is_verified BOOLEAN DEFAULT FALSE;"))
                    print("Added 'is_verified' column to 'users' table.")
                if "otp" not in columns:
                    conn.execute(text("ALTER TABLE users ADD COLUMN otp VARCHAR(6);"))
                    print("Added 'otp' column to 'users' table.")
                if "otp_expires_at" not in columns:
                    col_type = "TIMESTAMP" if "postgresql" in str(engine.url) else "DATETIME"
                    conn.execute(text(f"ALTER TABLE users ADD COLUMN otp_expires_at {col_type};"))
                    print("Added 'otp_expires_at' column to 'users' table.")
                conn.commit()
            print("Database columns migration completed.")
    except Exception as e:
        print(f"Database migration error: {e}")
        
    db = SessionLocal()
    
    # Check if already seeded
    if db.query(models.User).filter(models.User.email == "demo@rejectioniq.com").first():
        print("Database already seeded. Skipping.")
        db.close()
        return

    print("Seeding database...")

    # 1. Demo User
    demo_user = models.User(
        full_name="Arjun Shaik",
        email="demo@rejectioniq.com",
        password_hash=get_password_hash("demo1234"),
        cgpa=8.1,
        college="BITS Pilani",
        branch="Computer Science",
        graduation_year=2025,
        internship_count=1,
        project_count=3,
        skills=["Python", "React", "SQL", "Git", "FastAPI"],
        target_companies=["Google", "Microsoft", "Amazon", "Flipkart"],
        target_roles=["Software Engineer", "Backend Developer"],
        is_onboarded=True,
        is_verified=True,
        streak_count=5,
        total_rejections=8,
        resilience_score=7.2
    )
    db.add(demo_user)
    db.commit()
    db.refresh(demo_user)

    # 2. 8 Rejections
    today = datetime.date.today()
    rejections_data = [
        {"company": "JPMorgan", "role": "Software Engineer", "stage": "ATS Filter", "days": 1, "conf": 92.0, "oa": False, "rec": False, "tech": False},
        {"company": "Google", "role": "Backend SWE", "stage": "OA Rejection", "days": 4, "conf": 88.0, "oa": True, "rec": False, "tech": False},
        {"company": "Amazon", "role": "SDE-1", "stage": "Technical Round", "days": 12, "conf": 78.0, "oa": True, "rec": True, "tech": True},
        {"company": "Microsoft", "role": "Software Engineer", "stage": "HR Screen", "days": 6, "conf": 82.0, "oa": True, "rec": True, "tech": False},
        {"company": "Flipkart", "role": "SDE-1", "stage": "ATS Filter", "days": 2, "conf": 91.0, "oa": False, "rec": False, "tech": False},
        {"company": "Zoho", "role": "MTS", "stage": "Final Round", "days": 25, "conf": 74.0, "oa": True, "rec": True, "tech": True},
        {"company": "Infosys", "role": "Specialist Programmer", "stage": "OA Rejection", "days": 3, "conf": 85.0, "oa": True, "rec": False, "tech": False},
        {"company": "Goldman Sachs", "role": "Analyst", "stage": "Technical Round", "days": 15, "conf": 80.0, "oa": True, "rec": True, "tech": True},
    ]

    for r in rejections_data:
        rej = models.Rejection(
            user_id=demo_user.id,
            company_name=r["company"],
            role=r["role"],
            application_date=today - datetime.timedelta(days=r["days"] + random.randint(1, 5)),
            rejection_date=today - datetime.timedelta(days=random.randint(1, 5)),
            days_to_rejection=r["days"],
            oa_completed=r["oa"],
            recruiter_call=r["rec"],
            technical_round=r["tech"],
            rejection_stage=r["stage"],
            confidence_score=r["conf"],
            diagnosed_cause="Generated by Hybrid ML Engine",
            missing_keywords=["Docker", "Kubernetes", "AWS"] if r["tech"] else ["FastAPI", "Microservices"]
        )
        db.add(rej)
    
    db.commit()
    print("Added 8 rejections.")

    # Get JPMorgan rejection for Recovery Plan
    jp_rej = db.query(models.Rejection).filter(models.Rejection.company_name == "JPMorgan").first()
    
    # 3. Active Recovery Plan (7 tasks complete)
    for day in range(1, 31):
        week = ((day - 1) // 7) + 1
        is_complete = day <= 7
        task = models.RecoveryPlan(
            user_id=demo_user.id,
            rejection_id=jp_rej.id,
            day_number=day,
            week_number=week,
            task_title=f"Recovery Task Day {day}",
            task_desc="Complete 2 Leetcode problems" if week > 1 else "Fix Resume Keywords",
            category="Practice" if week > 1 else "Resume",
            completed=is_complete,
            completed_at=datetime.datetime.utcnow() if is_complete else None
        )
        db.add(task)
    
    db.commit()
    print("Added recovery plan tasks.")

    # 4. Resilience Logs
    for i in range(30):
        log = models.ResilienceLog(
            user_id=demo_user.id,
            mood_score=random.randint(4, 9),
            energy=random.randint(5, 10),
            logged_at=datetime.datetime.utcnow() - datetime.timedelta(days=i)
        )
        db.add(log)
    
    db.commit()
    print("Added resilience logs.")

    # 5. Peer Profiles (synthetic)
    companies = ["Google", "Microsoft", "Amazon", "Flipkart", "JPMorgan", "Zoho"]
    for i in range(500):
        peer = models.PeerProfile(
            company_name=random.choice(companies),
            role="Software Engineer",
            outcome="Offer" if random.random() > 0.7 else "Rejected",
            cgpa=round(random.uniform(7.0, 9.5), 1),
            internship_count=random.randint(0, 3),
            project_count=random.randint(2, 5),
            skills=["Python", "Java", "React"]
        )
        db.add(peer)
    
    db.commit()
    print("Added 500 peer profiles.")

    # 6. Milestones
    milestones = ["First Rejection Analysed", "First Recovery Plan", "7-Day Streak"]
    for m in milestones:
        ms = models.Milestone(
            user_id=demo_user.id,
            title=m,
            badge_icon="🏆"
        )
        db.add(ms)
    
    db.commit()
    print("Database seeding completed successfully.")
    db.close()

if __name__ == "__main__":
    seed_data()
